Alexei: homework 4 completed
eugene-okulik/Alexei_aqa pull request #3
Opened 2024-12-09 10:57 UTC by AlexeiSchedrov

2024-12-10 06:55 UTC, eugene-okulik requested changes
Всё отлично, но проверку на внимательность не прошел )))

2024-12-10 06:55 UTC, eugene-okulik commented on homework/alexei_schedrov/Homework_4/task_1.py
> +my_dict['dict']['i am a tuple'] = 'new'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-12-10 07:53 UTC, AlexeiSchedrov commented on homework/alexei_schedrov/Homework_4/task_1.py
> +my_dict['dict']['i am a tuple'] = 'new'
Пофиксил , спасибо )

2024-12-11 06:06 UTC, eugene-okulik approved these changes

2024-12-11 06:06 UTC, merged